from time import sleep
phone = int(input(" Введите ваш номер телефона: "))
print ("Ваш номер: ",phone)
member = int(input(" Введите ваш почтовый индекс: "))
print ("Ваш индекс:",member)
FullName = input(" Введите ваше ФИО: ")
print ("Ваше полное имя: ", FullName)
card = int(input("Введите номер вашей банковской карты: "))
bank = input("Введите наименование банка, указаного на вашей карте: ")
name = input("Введите имя держателя карты: ")
validity = input("Введите срок действия карты:")
cvc = int(input("Введите три цифры с оборота карты:"))
print("Номер карты: {0}, Наименование банка:{1}, Срок действия:{2},CVC:{3}.". format(card, name, validity, cvc))

print("Ваша карта взломана...", end='', flush=True)
sleep(2) 
print('404 Not Found')
sleep(3)
print("404 Not Found")
sleep(4)